apiVersion: apps/v1
kind: Deployment
metadata:
  name: $IMAGE_NAME-deployment
  labels:
    app: $IMAGE_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $IMAGE_NAME
  template:
    metadata:
      labels:
        app: $IMAGE_NAME
    spec:
      containers:
      - name: $IMAGE_NAME
        image: chikamalu/jvmapp:1.1.14-17
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: $IMAGE_NAME
spec:
  selector:
    app: $IMAGE_NAME
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080